# Generated by Django 3.1.14 on 2022-04-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام کالا')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس')),
                ('short_description', models.TextField(verbose_name='توضیح کوتاه')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیر فعال')),
                ('is_delete', models.BooleanField(verbose_name='حذف شده/نشده')),
            ],
        ),
    ]
