# Generated by Django 3.1.14 on 2022-04-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_auto_20220415_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد'),
        ),
    ]
