# Generated by Django 3.1.14 on 2022-05-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_auto_20220415_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان عکس')),
                ('Image', models.ImageField(upload_to=models.CharField(max_length=50, verbose_name='عنوان عکس'), verbose_name='عکس')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Images',
            field=models.ManyToManyField(null=True, to='product_module.ProductImages', verbose_name='عکسهای محصول'),
        ),
    ]
