# Generated by Django 3.1.14 on 2022-06-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_auto_20220614_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Images',
            field=models.ManyToManyField(blank=True, to='product_module.ProductImages', verbose_name='عکسهای محصول'),
        ),
    ]
