# Generated by Django 3.1.14 on 2022-06-17 12:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_module', '0011_productcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductBrand',
            new_name='ProductBrandModel',
        ),
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='ProductCategoryModel',
        ),
        migrations.RenameModel(
            old_name='ProductComment',
            new_name='ProductCommentModel',
        ),
        migrations.RenameModel(
            old_name='ProductGallery',
            new_name='ProductGalleryModel',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductModel',
        ),
        migrations.RenameModel(
            old_name='ProductTag',
            new_name='ProductTagModel',
        ),
    ]
