# Generated by Django 3.1.14 on 2022-06-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_auto_20220617_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcommentmodel',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='حذف شده/نشده'),
        ),
        migrations.AddField(
            model_name='productcommentmodel',
            name='is_read_admin',
            field=models.BooleanField(default=False, verbose_name='خوانده شده/نشده توسط ادمین'),
        ),
    ]
