# Generated by Django 3.1.14 on 2022-06-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0013_auto_20220617_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcommentmodel',
            name='is_read_admin',
            field=models.BooleanField(default=True, verbose_name='خوانده شده/نشده توسط ادمین'),
        ),
    ]
