# Generated by Django 3.1.14 on 2022-06-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_auto_20220415_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان بنر')),
                ('url', models.URLField(max_length=600, verbose_name='آدرس بنر')),
                ('image', models.ImageField(upload_to='images/SiteBanner/', verbose_name='تصویر بنر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
                ('position', models.CharField(choices=[('ProductListPageUrl', 'صفحه لیست محصولات'), ('ProductDetailPageUrl', 'صفحه جزئیات محصولات'), ('ArticlesPageUrl', 'لیست مقالات'), ('AboutPageUrl', 'درباره ما')], max_length=200)),
            ],
        ),
    ]
