# Generated by Django 3.1.14 on 2022-06-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_sitebanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitebanner',
            options={'verbose_name': 'بنر سایت', 'verbose_name_plural': 'بنر های سایت'},
        ),
    ]
