# Generated by Django 3.1.14 on 2022-06-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('fullname', models.CharField(max_length=300, verbose_name='نام و نام خانوادگی')),
                ('message', models.TextField(max_length=500, verbose_name='پیغام')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='خوانده شد / نشده')),
                ('created_data', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پیغام',
                'verbose_name_plural': 'پیغام ها',
            },
        ),
        migrations.CreateModel(
            name='SendNewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'ایمیل',
                'verbose_name_plural': 'ایمیل ها',
            },
        ),
    ]
