# Generated by Django 3.1.14 on 2022-06-17 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('url_title', models.CharField(max_length=100, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles_module.articlecategorymodel', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی مقاله',
                'verbose_name_plural': 'دسته بندی های مقاله',
            },
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(allow_unicode=True, max_length=400, verbose_name='عنوان در url')),
                ('CreatedTime', models.TimeField(auto_now_add=True, verbose_name='ساعت ایجاد مقاله')),
                ('CreatedDate', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد مقاله')),
                ('image', models.ImageField(upload_to='images/articles/', verbose_name='تصویر مقاله')),
                ('description', models.TextField(verbose_name='توضحات مقاله')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='پاک شده / پاک نشده')),
                ('article_category', models.ManyToManyField(blank=True, null=True, to='articles_module.ArticleCategoryModel', verbose_name='دسته بندی محصول')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='ArticleCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdTime', models.TimeField(auto_now_add=True, verbose_name='ساعت ایجاد مقاله')),
                ('createdDate', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد مقاله')),
                ('message', models.TextField(max_length=500, verbose_name='پیغام')),
                ('is_read_admin', models.BooleanField(default=False, verbose_name='خوانده شده/نشده توسط ادمین')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده/نشده')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles_module.articlemodel', verbose_name='مقاله')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles_module.articlecommentmodel', verbose_name='پیغام والد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیغام',
                'verbose_name_plural': 'پیغام ها',
            },
        ),
    ]
