# Generated by Django 3.1.14 on 2022-06-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecommentmodel',
            name='full_name',
            field=models.CharField(max_length=50, null=True, verbose_name='نام و نام خانوادگی'),
        ),
    ]
