# Generated by Django 3.1.14 on 2022-06-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_module', '0002_articlecommentmodel_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecommentmodel',
            name='full_name',
            field=models.CharField(max_length=50, verbose_name='نام و نام خانوادگی'),
        ),
    ]
