# Generated by Django 3.1.14 on 2022-04-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginAccountModel',
            new_name='LogInModel',
        ),
        migrations.RenameModel(
            old_name='RegisterModel',
            new_name='SingInModel',
        ),
    ]
