# Generated by Django 3.1.14 on 2022-04-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_auto_20220417_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='singinmodel',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام کاربری'),
        ),
    ]
