# Generated by Django 3.1.14 on 2022-04-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_auto_20220417_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singinmodel',
            name='email',
            field=models.CharField(max_length=50, verbose_name='ایمیل'),
        ),
    ]
