# Generated by Django 3.1.14 on 2022-06-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0007_auto_20220614_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images/user/', verbose_name='تصویر کاربر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about_us',
            field=models.TextField(blank=True, null=True, verbose_name='درباره من'),
        ),
    ]
